### ISSUE TITLE
Embed dynamic maps in 000652

### ISSUE THREAD

**Issue by juliaflanders** [Digital-Humanities-Quarterly/dhq-journal#9]
The author has provided full code (javascript, css, HTML) and also a link to a dynamic map on the web. Probably this should go in the DHQ annex, and be referenced using <ptr type="dhq-annex-embed"/>, the same way we referenced the author-contributed code in the comics special issue. 

We should consider whether it might be better to adapt the <media> element rather than using <ptr>.

**Comment by jawalsh** [comment]
The code has been hosted in the “dhq-annex”. Both maps are now available and ready for embedding in the article.

- <http://digitalhumanities.org/dhq-annex/000652/figure10/>
- <http://digitalhumanities.org/dhq-annex/000652/figure11/>
